# Generated by Django 3.2.9 on 2021-12-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_store_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='buyer_id',
            new_name='buyer',
        ),
    ]
