version: '3.8'

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 7000:7000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - myWe
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - myWe


networks:
  myWe:
    drive